version: '3.8'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7171:80"
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: db-user
            MYSQL_PASSWORD: db-password
        ports:
            - "9906:3306"

    node:
        container_name: node
        image: node:lts
        working_dir: /var/www/html
        volumes:
            - ./app:/var/www/html